[theme]
primaryColor = "#E37026"
backgroundColor = "rgba(0, 0, 0, 0.9)"
secondaryBackgroundColor = "rgba(14, 17, 23, 0.9)"
textColor = "#FFFFFF"
font = "sans serif"
borderColor="#E37026"
showWidgetBorder=true
