[theme]
primaryColor = "#E37026"
backgroundColor = "rgba(0, 0, 0, 0.5)"
secondaryBackgroundColor = "rgba(0, 0, 0, 0.9)"
textColor = "#FFFFFF"
font = "sans serif"
borderColor="#E37026"
showWidgetBorder=true
